// See https://aka.ms/new-console-template for more information
    
    int A = 440;
    int B = 494;
    int C = 262;
    int D = 294;
    int E = 330;
    int F = 349;
    int G = 392;

    int WholeNote= 4000;
      
    Console.BackgroundColor = ConsoleColor.Gray;
    Console.Clear();
    Console.ForegroundColor = ConsoleColor.White;
    Console.Beep(G + 391, WholeNote - 1000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Beep(E + 329, WholeNote - 1000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Beep(E + 329, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Green;
    Console.Beep(D + 293, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Magenta;
    Console.Beep(E + 329, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Yellow;
    Console.Beep(D + 293, WholeNote - 1000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkCyan;
    Console.Beep(D + 293, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkGreen;
    Console.Beep(C + 261, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkBlue;
    Console.Beep(D + 293, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkRed;
    Console.Beep(C + 261, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkGray;
    Console.Beep(E + 329, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkYellow;
    Console.Beep(C + 261, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkMagenta;
    Console.Beep(C + 261, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkBlue;
    Console.Beep(B, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Green;
    Console.Beep(C + 261, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Beep(B, WholeNote - 1000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Magenta;
    Console.Beep(A, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkYellow;
    Console.Beep(B, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkCyan;
    Console.Beep(A, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkRed;
    Console.Beep(D + 293, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Yellow;
    Console.Beep(A, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Beep(G, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Green;
    Console.Beep(A, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkRed;
    Console.Beep(G, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkYellow;
    Console.Beep(G, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Magenta;
    Console.Beep(F, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkBlue;
    Console.Beep(G, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkGreen;
    Console.Beep(F, WholeNote - 1000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkYellow;
    Console.Beep(E, WholeNote - 1000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Beep(E, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Green;
    Console.Beep(E, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Beep(F, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Magenta;
    Console.Beep(E, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkCyan;
    Console.Beep(A, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkGreen;
    Console.Beep(E, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Yellow;
    Console.Beep(D, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Cyan;
    Console.Beep(E, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkRed;
    Console.Beep(D, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Green;
    Console.Beep(D, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkRed;
    Console.Beep(C, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkBlue;
    Console.Beep(D, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkYellow;
    Console.Beep(C, WholeNote - 1000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Green;
    Console.Beep(B - 246, WholeNote - 1000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Blue;
    Console.Beep(G, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Red;
    Console.Beep(G + 392, WholeNote - 1000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Magenta;
    Console.Beep(E + 329, WholeNote - 1000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Cyan;
    Console.Beep(D + 293, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkGreen;
    Console.Beep(E + 329, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkBlue;
    Console.Beep(D + 293, WholeNote - 1000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkRed;
    Console.Beep(C + 261, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.Yellow;
    Console.Beep(D + 293, WholeNote - 3000);
    Console.Clear();
    Console.BackgroundColor = ConsoleColor.DarkMagenta;
